### ISSUE TITLE
Error size 16?

### ISSUE THREAD

**Issue by Kk2014kk** [mymonero/mymonero-mobile#66]
Got some monero put into MyMonero account on iPhone app, for the first time ever it’s come through at ring size 16 not 11, every time I try this send funds it says error occurred while getting decoy outputs ;error: count cannot be 11 . Any ideas?

**Comment by LivBoss** [comment]
Hi @Kk2014kk 

MyMonero were busy with some important upgrades for the hard fork, this is why our software was bugging.

We have since completed all upgrades and our systems are fully operational again.

You will need to update to our latest software.
We recommend uninstalling and reinstalling the app, since some devices do not update correctly without doing this.

Feel free to contact our support team at support@mymonero.com if you have any further questions or issues with our app.

**Comment by karlbuys** [comment]
Good day

Our latest release should have fixed the issue you were having. If you're still having difficulties, please re-open this thread
